model:
  # Global settings
  activation: gelu  # relu | gelu | sigmoid
  norm_layer: layernorm  # layernorm | batchnorm | groupnorm
  depth: 4
  dropout: 0.
  # Encoder
  embed_dim: 512
  dim_head: 64
  num_heads: 8
  decoder_embed_dim: 512
  decoder_dim_head: 64
  decoder_num_heads: 8
  mlp_time_embed: false
  # Conditioner
  cond_type: crossattn  # crossattn | mlp | stackffn
  cond_emb_type: embedding
  cond_cat_input: false
  cond_tokens: 1  # number of tokens to expand
  # Gene perturbation specific configs
  num_go_gnn_layers: 1
  gears_hidden_size: 512
  gears_mode: mlpparallel  # single | parallel | sequential | mlpparallel
  gears_mlp_layers: 1
  gears_norm: layernorm  # null | layernorm | batchnorm | groupnorm
  # Post conditioner
  post_cond_layers: 1
  post_cond_norm: batchnorm  # layernorm | batchnorm | groupnorm  (not used when post_cond_layers=1)
  # Decoder
  decoder_embed_type: embedder
  encoder_type: mlp  # attn | mlp | stackffn | mlpparallel | ffnparallel