model:
  # Global settings
  activation: gelu
  norm_layer: layernorm
  depth: 3
  dropout: 0.
  # Encoder
  embed_dim: 512
  dim_head: 64
  num_heads: 4
  decoder_embed_dim: 512
  decoder_dim_head: 64
  decoder_num_heads: 4
  mlp_time_embed: false
  # Conditioner
  cond_type: crossattn
  cond_emb_type: embedding
  cond_cat_input: false
  cond_tokens: 1
  # Gene perturbation specific configs
  num_go_gnn_layers: 1
  gears_hidden_size: 512
  gears_mode: mlpparallel
  gears_mlp_layers: 1
  gears_norm: layernorm
  # Post conditioner
  post_cond_layers: 1
  post_cond_norm: batchnorm
  # Decoder
  decoder_embed_type: embedder
  encoder_type: mlp
